package xtendfx.scene.transform;

/**
 * A couple of extension methods for manipulationg affine transformations.
 * See <a href="http://koehnlein.blogspot.de/2013/01/accumulating-javafx-transforms-with.html">my blog</a> for details.
 * 
 * @author koehnlein
 */
@SuppressWarnings("all")
public class TransformExtensions {
  /**
   * Accumulates another {@link Transform} in a given {@link Affine} using matrix multiplication.
   * When applying the combined transform, the original trafo is applied first.
   */
  public static Object leftMultiply(final /* Affine */Object it, final /* Transform */Object l) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mzx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mzy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field mzz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mzx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mzy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field mzz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mzx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mzy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field mzz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field mzx is undefined for the type TransformExtensions"
      + "\nThe method or field mzy is undefined for the type TransformExtensions"
      + "\nThe method or field mzz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ntx cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nty cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ntz cannot be resolved");
  }
  
  /**
   * Accumulates (multiplies) two {@link Transform}s into a new {@link Transform}.
   * When applying the transform, <code>r</code> is applied first.
   */
  public static /* Transform */Object operator_multiply(final /* Transform */Object l, final /* Transform */Object r) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Transform is undefined for the type TransformExtensions"
      + "\naffine cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\ntx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nty cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\ntz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ntx cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\ntx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nty cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\ntz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nty cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\ntx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\nty cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\ntz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ntz cannot be resolved");
  }
  
  /**
   * Applies a {@link Transform} to a {@link Point3D}.
   */
  public static /* Point3D */Object operator_multiply(final /* Transform */Object l, final /* Point3D */Object x) {
    throw new Error("Unresolved compilation problems:"
      + "\nPoint3D cannot be resolved."
      + "\nmxx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxy cannot be resolved"
      + "\n* cannot be resolved"
      + "\ny cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmxz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ntx cannot be resolved"
      + "\nmyx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyy cannot be resolved"
      + "\n* cannot be resolved"
      + "\ny cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmyz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nty cannot be resolved"
      + "\nmzx cannot be resolved"
      + "\n* cannot be resolved"
      + "\nx cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzy cannot be resolved"
      + "\n* cannot be resolved"
      + "\ny cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nmzz cannot be resolved"
      + "\n* cannot be resolved"
      + "\nz cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ntz cannot be resolved");
  }
  
  /**
   * Adds a translation to the given {@link Affine}
   */
  public static Object translate(final /* Affine */Object it, final double x, final double y) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved");
  }
  
  public static Object translate(final /* Affine */Object it, final double x, final double y, final double z) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved");
  }
  
  public static Object rotate(final /* Affine */Object it, final double angle) {
    throw new Error("Unresolved compilation problems:"
      + "\nRotate cannot be resolved.");
  }
  
  public static Object rotate(final /* Affine */Object it, final double angle, final double pivotX, final double pivotY) {
    throw new Error("Unresolved compilation problems:"
      + "\nRotate cannot be resolved.");
  }
  
  public static Object rotate(final /* Affine */Object it, final double angle, final double pivotX, final double pivotY, final double pivotZ) {
    throw new Error("Unresolved compilation problems:"
      + "\nRotate cannot be resolved.");
  }
  
  public static Object rotate(final /* Affine */Object it, final double angle, final double pivotX, final double pivotY, final double pivotZ, final /* Point3D */Object axis) {
    throw new Error("Unresolved compilation problems:"
      + "\nRotate cannot be resolved.");
  }
  
  public static Object rotate(final /* Affine */Object it, final double angle, final /* Point3D */Object axis) {
    throw new Error("Unresolved compilation problems:"
      + "\nRotate cannot be resolved.");
  }
  
  public static Object scale(final /* Affine */Object it, final double x, final double y) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions");
  }
  
  public static Object scale(final /* Affine */Object it, final double x, final double y, final double z) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field mzx is undefined for the type TransformExtensions"
      + "\nThe method or field mzx is undefined for the type TransformExtensions"
      + "\nThe method or field mzy is undefined for the type TransformExtensions"
      + "\nThe method or field mzy is undefined for the type TransformExtensions"
      + "\nThe method or field mzz is undefined for the type TransformExtensions"
      + "\nThe method or field mzz is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions"
      + "\nThe method or field tz is undefined for the type TransformExtensions");
  }
  
  public static Object scale(final /* Affine */Object it, final double x, final double y, final double pivotX, final double pivotY) {
    throw new Error("Unresolved compilation problems:"
      + "\nScale cannot be resolved.");
  }
  
  public static Object scale(final /* Affine */Object it, final double x, final double y, final double z, final double pivotX, final double pivotY, final double pivotZ) {
    throw new Error("Unresolved compilation problems:"
      + "\nScale cannot be resolved.");
  }
  
  public static Object shear(final /* Affine */Object it, final double x, final double y) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved");
  }
  
  public static Object shear(final /* Affine */Object it, final double x, final double y, final double pivotX, final double pivotY) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\nThe method or field mxx is undefined for the type TransformExtensions"
      + "\nThe method or field mxy is undefined for the type TransformExtensions"
      + "\nThe method or field mxz is undefined for the type TransformExtensions"
      + "\nThe method or field myx is undefined for the type TransformExtensions"
      + "\nThe method or field myy is undefined for the type TransformExtensions"
      + "\nThe method or field myz is undefined for the type TransformExtensions"
      + "\nThe method or field tx is undefined for the type TransformExtensions"
      + "\nThe method or field ty is undefined for the type TransformExtensions"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n- cannot be resolved");
  }
}
